# site settings
title: Ravi Bhandia
subtitle: Portfolio
email: ravi@bhandia.com
description: Hi! I'm Ravi. Welcome to my website! I'm a californian born and raised (never lived anywhere else). I'm passionate about the environment, education equality, and finance. I recently graduated from UC Berkeley with a Masters in Operations Research where I had the opportunity to learn and practice data science and product skills. I completed my bachelors at USC in Chemical Engineering with a minor in Business Finance. Here are a selection of projects that I would like to share with you! 
baseurl: ""
url: "https://ravibhandia.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
